package com.amazonaws.mobile.api;

//
//  CloudLogicAPIFactory.java
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.10
//

/**
 * Produces instances of Cloud Logic API configuration.
 */
public class CloudLogicAPIFactory {

    private CloudLogicAPIFactory() {}

    /**
     * Gets the configured micro-service instances.
     * @return
     */
    public static CloudLogicAPIConfiguration[] getAPIs() {
        final CloudLogicAPIConfiguration[] apis = new CloudLogicAPIConfiguration[] {
                new CloudLogicAPIConfiguration("routes",
                                              "used to perform transactions on the ROUTES table",
                                              "https://pnld4ilt93.execute-api.us-east-1.amazonaws.com/Development",
                                              new String[] {
                                                  "/getRoutes",
                                                  "/storeRoute",
                                                  "/useRoute",
                                                  "/getRoutes/123",
                                                  "/storeRoute/123",
                                                  "/useRoute/123",
                                              },
                                              com.amazonaws.mobile.api.idpnld4ilt93.RoutesMobileHubClient.class),
                new CloudLogicAPIConfiguration("biker",
                                              "used to manipulate database for a user or biker in the biker table",
                                              "https://pokd38pxx7.execute-api.us-east-1.amazonaws.com/Development",
                                              new String[] {
                                                  "/items",
                                                  "/path-747",
                                                  "/items/123",
                                                  "/path-747/123",
                                              },
                                              com.amazonaws.mobile.api.idpokd38pxx7.BikerMobileHubClient.class),
        };

        return apis;
    }
}
